routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('template');
// });

Route::get('/','MainController@index');

Route::get('/about','MainController@about');
Route::get('/features','MainController@features');

// For Profile
Route::resource('/profile','ProfileController');

// For New Story
Route::resource('/newstory','PostController');

// For Comments
Route::resource('/comment','CommentController');

// For Categories (only Admin)
Route::resource('/admin/category','Admin\CategoryController');

// For Posts (only Admin)
Route::resource('/admin/post','Admin\PostController');

// For Operations (only Admin)
// For Testing (e.g -> email, ..)
Route::get('/admin/operation','Admin\OperationController@index')->name('admin.operation');

Route::post('/admin/sendemail','Admin\OperationController@sendemail')->name('admin.sendemail');

Auth::routes();

Route::get('/home', 'HomeController@index')
		->middleware('is_admin')
		->name('home');

resources/views/about.blade.php
@extends('template')

@section('content')
	<h1>About Page</h1>
@endsection

resources/views/features.blade.php
@extends('template')

@section('content')
	<h1>About Page</h1>
@endsection

resources/views/first.blade.php
@extends('template')
@section('content')
	<nav class="navbar navbar-expand navbar-light bg-white">
		<div class="container">
			<a class="navbar-brand mx-3" href="#"><small>All Articles</small></a>

			<div class="collapse navbar-collapse">
			    <ul class="navbar-nav ml-auto">
				    <li class="nav-item dropdown mx-2">
				        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				          Categories
				        </a>
<div class="dropdown-menu" aria-labelledby="navbarDropdown">
	@foreach($categories as $category)
  	<a class="dropdown-item" href="/?category_id={{$category->id}}">{{$category->name}}</a>
  	@endforeach
</div>
				    </li>
			    </ul>
			    <form class="form-inline my-2 my-lg-0">
			      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
			    </form>
			</div>
		</div>
	</nav>

	<section class="py-5 bg-mylight">
	  <div class="container">
	    <div class="row">
	    	@foreach($posts as $post)
	    	<div class="col-md-4">
    			<div class="card" style="border-radius: 1rem;">
    				<a href="{{route('newstory.show',$post->id)}}" class="mb-2 d-block" style="cursor: pointer !important;text-decoration: none;">
					    <img class="card-img-top" src="{{ asset($post->image) }}" alt="Card image cap">
					  	<div class="card-img-overlay">
							<span class="card-title">{{$post->category->name}}</span>
						</div>
					    <div class="card-body">
						  	<p class="text-dark">{{$post->user->name}}</p>
							<p>{{$post->title}}</p>
							
						    <p class="lead small mb-0 text-secondary">{{ $post->created_at->toFormattedDateString() }}</p>
					    </div>
					</a>
				</div>
    		</div>
    		@endforeach
	    </div>
	  </div>
	</section>

	<section class=" py-3 bg-white">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<!-- <nav aria-label="Page navigation example">
					  <ul class="pagination justify-content-end mb-0">
					    <li class="page-item disabled">
					      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
					    </li>
					    <li class="page-item"><a class="page-link" href="#">1</a></li>
					    <li class="page-item"><a class="page-link" href="#">2</a></li>
					    <li class="page-item"><a class="page-link" href="#">3</a></li>
					    <li class="page-item">
					      <a class="page-link" href="#">Next</a>
					    </li>
					  </ul>
					</nav> -->
					{{ $posts->links() }}
				</div>
				
			</div>
		</div>
	</section>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/login.blade.php
@extends('template')

@section('content')
	<h1>About Page</h1>
@endsection

resources/views/postdetail.blade.php
@extends('template')
@section('content')
	<section class="py-5 bg-mylight">
	  <div class="container">
	    <div class="row">
	    	<div class="col-md-6">
    			<h2 class="mb-5">{{$post->title}}</h2>

    			<div class="media my-5">
    				@if($post->user->profile == 'profilepic')
					  <img src="{{asset('template/images/profile.png')}}" class="mr-3 rounded-circle" width="50" alt="...">
					@else
					  <img src="{{asset($post->user->profile)}}" class="mr-3 rounded-circle" width="50" alt="...">
					@endif
				  <div class="media-body">
				    <h5 class="mt-0">{{$post->user->name}}</h5>
				    <span>{{$post->created_at->toFormattedDateString()}}</span>
				  </div>
				</div>
				<button class="btn btn-lg btn-outline-success" style="border-radius: 2rem !important;"><i class="fas fa-tags"></i> <span class="pl-2"><a href="/?category_id={{$post->category->id}}" style="text-decoration: none;color: inherit;">{{$post->category->name}}</a></span></button>

				@if(Auth::check() && ($post->user_id == Auth::user()->id))
				<div class="form-group mt-3">
					<a href="{{route('newstory.edit',$post->id)}}" class="btn btn-warning">Edit</a>

				<form method="post" action="{{route('newstory.destroy',$post->id)}}" class="d-inline-block">
					<input type="hidden" name="_method" value="DELETE">
					@csrf
					<input type="submit" class="btn btn-danger" value="Delete">
				</form>
				</div>
					
				@endif
    		</div>
    		<div class="col-md-6 py-3">
    			<img src="{{asset($post->image)}}" class="img-fluid">
    		</div>
	    </div>
	  </div>
	</section>

	<section class="py-5 bg-white">
	  <div class="container">
	    <div class="row my-5">
	    	<div class="col-md-8 offset-md-2">
	    		<p class="lead">
	    			{!!$post->body!!}
	    		</p>
	    	</div>
	    </div>

	    <div class="row">
	    	<div class="col-md-8 offset-md-2">
	    		<!-- <form method="post" action="{{route('comment.store')}}"> -->
	    			@csrf
	    			<input type="hidden" name="post_id" value="{{$post->id}}" id="post_id">
	    			<div class="form-group">
	    				<textarea class="form-control {{ $errors->has('comment') ? ' is-invalid' : '' }}" rows="5" name="comment" placeholder="Write Comments..." id="comment"></textarea>
@if ($errors->has('comment'))
    <span class="invalid-feedback" role="alert">
        <strong>{{ $errors->first('comment') }}</strong>
    </span>
@endif
	    			</div>

	    			<!-- <input type="submit" name="btn" value="Post" class="btn btn-success"> -->
	    			<button class="btn btn-success" id="givecomment">Post</button>
	    		<!-- </form> -->
	    	</div>

	    	<div class="col-md-8 offset-md-2 my-5">
	    		<div class="card my-3 shadow">
				  <h5 class="card-header">Comments..</h5>
				  <div class="card-body" >
				  	<div id="comments"></div>

					

  				  </div>
				</div>
	    	</div>
	    </div>
	  </div>
	</section>
@endsection
@section('script')
	<script type="text/javascript">
		comments();

		$('#givecomment').click(function (e) {
			// body...
			e.preventDefault();
			var comment = $('#comment').val();
			var post_id = $('#post_id').val();

			// alert(comment + post_id);

			$.ajaxSetup({
			    headers: {
			        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
			    }
			});

			$.post('/comment',
                {post_id:post_id,comment:comment},
                function (response) {
                // alert(response.success);
               comments();
            });
		});

		function comments() {

			var post_id = $('#post_id').val();

			$.ajaxSetup({
			    headers: {
			        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
			    }
			});

			$.get('/comment',
                {post_id:post_id},
                function (response) {
                console.log(response.data);
                var html = '';
                var i =0;
                var data = response.data.slice(0,3);
                $.each(data,function (i,v) {
                	// console.log(v.body);
                	html += '<div class="media mb-5">';

                	if(v.user.profile == 'profilepic'){
                		html += '<img src="{{asset('template/images/profile.png')}}" class="mr-3 img-fluid rounded-circle" width="30" alt="...">';
                	}else{
                		html += '<img src="'+v.user.profile+'" class="mr-3 img-fluid rounded-circle" width="30" alt="...">';
                	}
                	

                		html += '<div class="media-body">'+
					    '<h5 class="mt-0">'+v.user.name+
					    '<small class="float-right">'+v.created_at+'</small>'+
					    '</h5>'+v.body+'</div>'+
					'</div>';
					i++;

					
					
                });
                if (response.data.length >3 && i != response.data.length) {
						html += '<p style="cursor: pointer;" id="morecomments">More Comments...</p>';
					}
                $('#comments').html(html);
            });
		}


		$('#comments').on('#morecomments','click',function (e) {
			e.preventDefault();
			
		})
	</script>
@endsection

resources/views/template.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>MMIT Bootcamp</title>

	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <link rel="shortcut icon" href="{{ asset('template/images/favicon.ico')}}" type="image/x-icon">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ asset('template/css/bootstrap.min.css') }}">

    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="{{ asset('template/fontawesome/css/all.min.css') }}">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ asset('template/css/custom.css') }}">

    <!-- For summernote -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote-bs4.css" rel="stylesheet">
    
    <!-- Jquery -->
    <script type="text/javascript" src="{{ asset('template/js/jquery.min.js') }}"></script>
    
    <!-- Bootstrap JS -->
    <script type="text/javascript" src="{{ asset('template/js/bootstrap.bundle.min.js') }}"></script>

    <!-- For summernote -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote-bs4.js"></script>
</head>
<body>
	
	<!-- Header -->
	@include('part.header')

	@yield('content')

	<!-- Footer -->
	@include('part.footer')

    <script>
      $('#summernote').summernote({
        placeholder: 'Blog Post..',
        tabsize: 2,
        height: 400
      });

      // For Profile Upload
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('.your_picture_image')
                        .attr('src', e.target.result);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>

    @yield('script')
</body>
</html>