routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('template');
// });

Route::get('/','MainController@index');

Route::get('/about','MainController@about');
Route::get('/features','MainController@features');

// For Profile
Route::resource('/profile','ProfileController');

// For New Story
Route::resource('/newstory','PostController');

// For Comments
Route::resource('/comment','CommentController');

// For Categories (only Admin)
Route::resource('/admin/category','Admin\CategoryController');

// For Posts (only Admin)
Route::resource('/admin/post','Admin\PostController');

// For Operations (only Admin)
// For Testing (e.g -> email, ..)
Route::get('/admin/operation','Admin\OperationController@index')->name('admin.operation');

Route::post('/admin/sendemail','Admin\OperationController@sendemail')->name('admin.sendemail');

Auth::routes();

Route::get('/home', 'HomeController@index')
		->middleware('is_admin')
		->name('home');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    protected $fillable = [
        'name',
    ];

    public function posts()
    {
        return $this->hasMany('App\Post');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Category;

class CategoryController extends Controller
{
    public function __construct()
    {
        // $this->middleware('auth');

        // User must be a admin and authnenticated
        $this->middleware('is_admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        //
        $categories = Category::all();
        return view('admin.category.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $category = Category::find($id);

        // dd($category->posts);

        if(!$category->posts->isEmpty()){
            return redirect()->route('category.index')->with('status','You Cannot Delete That Category!');
        }else{
            $category->delete();
            return redirect()->route('category.index');
        }

        
    }
}

resources/views/admin/category/index.blade.php
@extends('template')

@section('content')
<div class="container">
    <div class="row justify-content-center my-5">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Category List
                    <a href="#" class="btn btn-success float-right">Add</a>
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-danger" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <table class="table">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th>Edit</th>
                                <th>Delete😇</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($categories as $category)
                            <tr>
                                <td>{{$category->id}}</td>
                                <td>{{$category->name}}</td>
                                <td>
                                    <a href="{{route('category.edit',$category->id)}}" class="btn btn-warning btn-sm">Edit</a>
                                </td>
                                <td>
                                    <form method="post" action="{{route('category.destroy',$category->id)}}" onsubmit="return confirm('Are You Sure To Delete?')">
                                        @csrf
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="submit" class="btn btn-danger btn-sm" value="Delete">
                                    </form>
                                    
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
    <script type="text/javascript">
        $('.alert').fadeOut(3000);
    </script>
@endsection